apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: example-todo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: example-todo
    spec:
      containers:
      - name: example-todo
        image: "gabrtv/example-todo:latest"
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3000
        env:
        - name: REDIS_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: redis-creds
              key: hostname
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: redis-creds
              key: port        
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-creds
              key: primaryKey   

